### ISSUE TITLE
Should use `context.scene.bc.shape = bpy.data.objects[object_namestripped]` here

### ISSUE THREAD

**Issue by proxeIO** [NewMediaSupply/NMS_BCs#1]
https://github.com/NewMediaSupply/NMS_BCs/blob/3b3f397c515289fe673abfa397bd896e4af35eba/__init__.py#L78

**Comment by proxeIO** [comment]
Allowing the tool to work in any scene.

**Comment by NewMediaSupply** [comment]
Thanks, I'll check that out in 1 or 2 days.

**Comment by NewMediaSupply** [comment]
Ah, fixed. Checked. Not so familiar with github, but I suppose I have to close with comment.
